development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yandex_auth_app_id: <%= ENV["YA_AUTH_APP_ID"] %>
  yandex_auth_secret: <%= ENV["YA_AUTH_SECRET"] %>


production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  yandex_auth_app_id: <%= ENV["YA_AUTH_APP_ID"] %>
  yandex_auth_secret: <%= ENV["YA_AUTH_SECRET"] %>
